<?xml version="1.0" encoding="UTF-8"?>
<gml spec="1.0">
  <tag>
    <header>
      <client>
        <name>draw3d</name>
        <version>0.1</version>
      </client>
      <environment>
        <offset>
          <x>-0.5</x>
          <y>-0.5</y>
          <z>-0.5</z>
        </offset>
        <rotation>
          <x>0.0</x>
          <y>0.0</y>
          <z>0.0</z>
        </rotation>
        <up>
          <x>0.0</x>
          <y>-1.0</y>
          <z>0.0</z>
        </up>
        <screenBounds>
          <x>1024.0</x>
          <y>1024.0</y>
          <z>1024.0</z>
        </screenBounds>
        <origin>
          <x>0.0</x>
          <y>0.0</y>
          <z>0.0</z>
        </origin>
        <realScale>
          <x>200.0</x>
          <y>200.0</y>
          <z>200.0</z>
          <unit>mm</unit>
        </realScale>
      </environment>
    </header>
    <drawing/>
  </tag>
</gml>
